### ISSUE TITLE
UDP Checksum Not working

### ISSUE THREAD

**Issue by JackOBrien** [JackOBrien/Virtual-Network#2]
Looks like IPv4 is working, but I think UDP is broken. When I turn on the UDP checksum validation in Wireshark, both the UDP checksum we make and the one we didn't have a bad checksum. 
![capture](https://cloud.githubusercontent.com/assets/5542663/4694851/88c30ec0-57d9-11e4-912c-1cb75b19c7c0.PNG)

**Comment by JackOBrien** [comment]
Talked to Kalafut. The first one failing _is_ due to UDP checksum offload like it says in Wireshark, but the second is failing because we coded it wrong. Don't know why yet.

**Comment by JackOBrien** [comment]
The code as of right now just adds 20 to the UDP checkum at the very end (after flipping the bits). This fixes the problem. **We need to figure out why**

**Comment by JackOBrien** [comment]
I found the problem! It was my own fault, I misread the Wiki page about IPv4 Pseudo Headers. I was doing the IPv4 length field instead of the UDP length field. Works now

**Comment by MeganMaher** [comment]
why
